package com.jicl.entity;

import java.util.ArrayList;
import java.util.List;

public class AnnouncementExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    public AnnouncementExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAnncIdIsNull() {
            addCriterion("annc_id is null");
            return (Criteria) this;
        }

        public Criteria andAnncIdIsNotNull() {
            addCriterion("annc_id is not null");
            return (Criteria) this;
        }

        public Criteria andAnncIdEqualTo(Integer value) {
            addCriterion("annc_id =", value, "anncId");
            return (Criteria) this;
        }

        public Criteria andAnncIdNotEqualTo(Integer value) {
            addCriterion("annc_id <>", value, "anncId");
            return (Criteria) this;
        }

        public Criteria andAnncIdGreaterThan(Integer value) {
            addCriterion("annc_id >", value, "anncId");
            return (Criteria) this;
        }

        public Criteria andAnncIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("annc_id >=", value, "anncId");
            return (Criteria) this;
        }

        public Criteria andAnncIdLessThan(Integer value) {
            addCriterion("annc_id <", value, "anncId");
            return (Criteria) this;
        }

        public Criteria andAnncIdLessThanOrEqualTo(Integer value) {
            addCriterion("annc_id <=", value, "anncId");
            return (Criteria) this;
        }

        public Criteria andAnncIdIn(List<Integer> values) {
            addCriterion("annc_id in", values, "anncId");
            return (Criteria) this;
        }

        public Criteria andAnncIdNotIn(List<Integer> values) {
            addCriterion("annc_id not in", values, "anncId");
            return (Criteria) this;
        }

        public Criteria andAnncIdBetween(Integer value1, Integer value2) {
            addCriterion("annc_id between", value1, value2, "anncId");
            return (Criteria) this;
        }

        public Criteria andAnncIdNotBetween(Integer value1, Integer value2) {
            addCriterion("annc_id not between", value1, value2, "anncId");
            return (Criteria) this;
        }

        public Criteria andAnncTitleIsNull() {
            addCriterion("annc_title is null");
            return (Criteria) this;
        }

        public Criteria andAnncTitleIsNotNull() {
            addCriterion("annc_title is not null");
            return (Criteria) this;
        }

        public Criteria andAnncTitleEqualTo(String value) {
            addCriterion("annc_title =", value, "anncTitle");
            return (Criteria) this;
        }

        public Criteria andAnncTitleNotEqualTo(String value) {
            addCriterion("annc_title <>", value, "anncTitle");
            return (Criteria) this;
        }

        public Criteria andAnncTitleGreaterThan(String value) {
            addCriterion("annc_title >", value, "anncTitle");
            return (Criteria) this;
        }

        public Criteria andAnncTitleGreaterThanOrEqualTo(String value) {
            addCriterion("annc_title >=", value, "anncTitle");
            return (Criteria) this;
        }

        public Criteria andAnncTitleLessThan(String value) {
            addCriterion("annc_title <", value, "anncTitle");
            return (Criteria) this;
        }

        public Criteria andAnncTitleLessThanOrEqualTo(String value) {
            addCriterion("annc_title <=", value, "anncTitle");
            return (Criteria) this;
        }

        public Criteria andAnncTitleLike(String value) {
            addCriterion("annc_title like", value, "anncTitle");
            return (Criteria) this;
        }

        public Criteria andAnncTitleNotLike(String value) {
            addCriterion("annc_title not like", value, "anncTitle");
            return (Criteria) this;
        }

        public Criteria andAnncTitleIn(List<String> values) {
            addCriterion("annc_title in", values, "anncTitle");
            return (Criteria) this;
        }

        public Criteria andAnncTitleNotIn(List<String> values) {
            addCriterion("annc_title not in", values, "anncTitle");
            return (Criteria) this;
        }

        public Criteria andAnncTitleBetween(String value1, String value2) {
            addCriterion("annc_title between", value1, value2, "anncTitle");
            return (Criteria) this;
        }

        public Criteria andAnncTitleNotBetween(String value1, String value2) {
            addCriterion("annc_title not between", value1, value2, "anncTitle");
            return (Criteria) this;
        }

        public Criteria andTopFlagIsNull() {
            addCriterion("top_flag is null");
            return (Criteria) this;
        }

        public Criteria andTopFlagIsNotNull() {
            addCriterion("top_flag is not null");
            return (Criteria) this;
        }

        public Criteria andTopFlagEqualTo(Boolean value) {
            addCriterion("top_flag =", value, "topFlag");
            return (Criteria) this;
        }

        public Criteria andTopFlagNotEqualTo(Boolean value) {
            addCriterion("top_flag <>", value, "topFlag");
            return (Criteria) this;
        }

        public Criteria andTopFlagGreaterThan(Boolean value) {
            addCriterion("top_flag >", value, "topFlag");
            return (Criteria) this;
        }

        public Criteria andTopFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("top_flag >=", value, "topFlag");
            return (Criteria) this;
        }

        public Criteria andTopFlagLessThan(Boolean value) {
            addCriterion("top_flag <", value, "topFlag");
            return (Criteria) this;
        }

        public Criteria andTopFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("top_flag <=", value, "topFlag");
            return (Criteria) this;
        }

        public Criteria andTopFlagIn(List<Boolean> values) {
            addCriterion("top_flag in", values, "topFlag");
            return (Criteria) this;
        }

        public Criteria andTopFlagNotIn(List<Boolean> values) {
            addCriterion("top_flag not in", values, "topFlag");
            return (Criteria) this;
        }

        public Criteria andTopFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("top_flag between", value1, value2, "topFlag");
            return (Criteria) this;
        }

        public Criteria andTopFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("top_flag not between", value1, value2, "topFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_announcement
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}