package com.jicl.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_blog_tag
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class BlogTag implements Serializable {
    /**
     * Database Column Remarks:
     *   博客id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_tag.blog_id
     *
     * @mbg.generated
     */
    private Integer blogId;

    /**
     * Database Column Remarks:
     *   标签id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_tag.tags_id
     *
     * @mbg.generated
     */
    private Integer tagsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_blog_tag
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_tag.blog_id
     *
     * @return the value of t_blog_tag.blog_id
     *
     * @mbg.generated
     */
    public Integer getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_tag.blog_id
     *
     * @param blogId the value for t_blog_tag.blog_id
     *
     * @mbg.generated
     */
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_tag.tags_id
     *
     * @return the value of t_blog_tag.tags_id
     *
     * @mbg.generated
     */
    public Integer getTagsId() {
        return tagsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_tag.tags_id
     *
     * @param tagsId the value for t_blog_tag.tags_id
     *
     * @mbg.generated
     */
    public void setTagsId(Integer tagsId) {
        this.tagsId = tagsId;
    }
}