package com.jicl.entity;

import java.io.Serializable;

import lombok.Builder;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_blog_tag
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
@Builder
public class BlogTag implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_tag.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   博客id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_tag.blog_id
     *
     * @mbg.generated
     */
    private Integer blogId;

    /**
     * Database Column Remarks:
     *   标签id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_tag.tag_id
     *
     * @mbg.generated
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_blog_tag
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}