package com.jicl.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_blog
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Blog implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.blog_id
     *
     * @mbg.generated
     */
    private Integer blogId;

    /**
     * Database Column Remarks:
     *   博主id，对应用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   博客描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.blog_desc
     *
     * @mbg.generated
     */
    private String blogDesc;

    /**
     * Database Column Remarks:
     *   是否推荐
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.recommend
     *
     * @mbg.generated
     */
    private Boolean recommend;

    /**
     * Database Column Remarks:
     *   转载声明是否开启
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.share_flag
     *
     * @mbg.generated
     */
    private Boolean shareFlag;

    /**
     * Database Column Remarks:
     *   博客类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.type_id
     *
     * @mbg.generated
     */
    private Long typeId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   首图地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.first_picture_addr
     *
     * @mbg.generated
     */
    private String firstPictureAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.published
     *
     * @mbg.generated
     */
    private Boolean published;

    /**
     * Database Column Remarks:
     *   博客标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.blog_title
     *
     * @mbg.generated
     */
    private String blogTitle;

    /**
     * Database Column Remarks:
     *   博客浏览次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.blog_views
     *
     * @mbg.generated
     */
    private Integer blogViews;

    /**
     * Database Column Remarks:
     *   是否开启赞赏
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.appreciation_flag
     *
     * @mbg.generated
     */
    private Boolean appreciationFlag;

    /**
     * Database Column Remarks:
     *   是否开启评论
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.commentabled
     *
     * @mbg.generated
     */
    private Boolean commentabled;

    /**
     * Database Column Remarks:
     *   博客评论次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.blog_comments
     *
     * @mbg.generated
     */
    private Integer blogComments;

    /**
     * Database Column Remarks:
     *   博客内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.blog_content
     *
     * @mbg.generated
     */
    private String blogContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_blog
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.blog_id
     *
     * @return the value of t_blog.blog_id
     *
     * @mbg.generated
     */
    public Integer getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.blog_id
     *
     * @param blogId the value for t_blog.blog_id
     *
     * @mbg.generated
     */
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.user_id
     *
     * @return the value of t_blog.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.user_id
     *
     * @param userId the value for t_blog.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.blog_desc
     *
     * @return the value of t_blog.blog_desc
     *
     * @mbg.generated
     */
    public String getBlogDesc() {
        return blogDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.blog_desc
     *
     * @param blogDesc the value for t_blog.blog_desc
     *
     * @mbg.generated
     */
    public void setBlogDesc(String blogDesc) {
        this.blogDesc = blogDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.recommend
     *
     * @return the value of t_blog.recommend
     *
     * @mbg.generated
     */
    public Boolean getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.recommend
     *
     * @param recommend the value for t_blog.recommend
     *
     * @mbg.generated
     */
    public void setRecommend(Boolean recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.share_flag
     *
     * @return the value of t_blog.share_flag
     *
     * @mbg.generated
     */
    public Boolean getShareFlag() {
        return shareFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.share_flag
     *
     * @param shareFlag the value for t_blog.share_flag
     *
     * @mbg.generated
     */
    public void setShareFlag(Boolean shareFlag) {
        this.shareFlag = shareFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.type_id
     *
     * @return the value of t_blog.type_id
     *
     * @mbg.generated
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.type_id
     *
     * @param typeId the value for t_blog.type_id
     *
     * @mbg.generated
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.create_time
     *
     * @return the value of t_blog.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.create_time
     *
     * @param createTime the value for t_blog.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.update_time
     *
     * @return the value of t_blog.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.update_time
     *
     * @param updateTime the value for t_blog.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.first_picture_addr
     *
     * @return the value of t_blog.first_picture_addr
     *
     * @mbg.generated
     */
    public String getFirstPictureAddr() {
        return firstPictureAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.first_picture_addr
     *
     * @param firstPictureAddr the value for t_blog.first_picture_addr
     *
     * @mbg.generated
     */
    public void setFirstPictureAddr(String firstPictureAddr) {
        this.firstPictureAddr = firstPictureAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.published
     *
     * @return the value of t_blog.published
     *
     * @mbg.generated
     */
    public Boolean getPublished() {
        return published;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.published
     *
     * @param published the value for t_blog.published
     *
     * @mbg.generated
     */
    public void setPublished(Boolean published) {
        this.published = published;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.blog_title
     *
     * @return the value of t_blog.blog_title
     *
     * @mbg.generated
     */
    public String getBlogTitle() {
        return blogTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.blog_title
     *
     * @param blogTitle the value for t_blog.blog_title
     *
     * @mbg.generated
     */
    public void setBlogTitle(String blogTitle) {
        this.blogTitle = blogTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.blog_views
     *
     * @return the value of t_blog.blog_views
     *
     * @mbg.generated
     */
    public Integer getBlogViews() {
        return blogViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.blog_views
     *
     * @param blogViews the value for t_blog.blog_views
     *
     * @mbg.generated
     */
    public void setBlogViews(Integer blogViews) {
        this.blogViews = blogViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.appreciation_flag
     *
     * @return the value of t_blog.appreciation_flag
     *
     * @mbg.generated
     */
    public Boolean getAppreciationFlag() {
        return appreciationFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.appreciation_flag
     *
     * @param appreciationFlag the value for t_blog.appreciation_flag
     *
     * @mbg.generated
     */
    public void setAppreciationFlag(Boolean appreciationFlag) {
        this.appreciationFlag = appreciationFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.commentabled
     *
     * @return the value of t_blog.commentabled
     *
     * @mbg.generated
     */
    public Boolean getCommentabled() {
        return commentabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.commentabled
     *
     * @param commentabled the value for t_blog.commentabled
     *
     * @mbg.generated
     */
    public void setCommentabled(Boolean commentabled) {
        this.commentabled = commentabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.blog_comments
     *
     * @return the value of t_blog.blog_comments
     *
     * @mbg.generated
     */
    public Integer getBlogComments() {
        return blogComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.blog_comments
     *
     * @param blogComments the value for t_blog.blog_comments
     *
     * @mbg.generated
     */
    public void setBlogComments(Integer blogComments) {
        this.blogComments = blogComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.blog_content
     *
     * @return the value of t_blog.blog_content
     *
     * @mbg.generated
     */
    public String getBlogContent() {
        return blogContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.blog_content
     *
     * @param blogContent the value for t_blog.blog_content
     *
     * @mbg.generated
     */
    public void setBlogContent(String blogContent) {
        this.blogContent = blogContent;
    }
}