package com.jicl.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_blog
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class Blog implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.blog_id
     *
     * @mbg.generated
     */
    private Integer blogId;

    /**
     * Database Column Remarks:
     *   博主id，对应用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   博客标志：1-原创，2-转载，3-翻译
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.blog_flag
     *
     * @mbg.generated
     */
    private String blogFlag;

    /**
     * Database Column Remarks:
     *   博客描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.blog_desc
     *
     * @mbg.generated
     */
    private String blogDesc;

    /**
     * Database Column Remarks:
     *   是否推荐
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.recommend
     *
     * @mbg.generated
     */
    private Boolean recommend;

    /**
     * Database Column Remarks:
     *   转载声明是否开启
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.share_flag
     *
     * @mbg.generated
     */
    private Boolean shareFlag;

    /**
     * Database Column Remarks:
     *   博客类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.type_id
     *
     * @mbg.generated
     */
    private Integer typeId;

    /**
     * Database Column Remarks:
     *   博客标签字符串，格式：,1,2,3,4,5,
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.tag_id_str
     *
     * @mbg.generated
     */
    private String tagIdStr;

    /**
     * Database Column Remarks:
     *   首图地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.first_picture_addr
     *
     * @mbg.generated
     */
    private String firstPictureAddr;

    /**
     * Database Column Remarks:
     *   是否发布：0-草稿 1-发布
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.published
     *
     * @mbg.generated
     */
    private Boolean published;

    /**
     * Database Column Remarks:
     *   博客标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.blog_title
     *
     * @mbg.generated
     */
    private String blogTitle;

    /**
     * Database Column Remarks:
     *   博客浏览次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.blog_views
     *
     * @mbg.generated
     */
    private Integer blogViews;

    /**
     * Database Column Remarks:
     *   是否开启赞赏
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.appreciation_flag
     *
     * @mbg.generated
     */
    private Boolean appreciationFlag;

    /**
     * Database Column Remarks:
     *   是否开启评论
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.commentabled
     *
     * @mbg.generated
     */
    private Boolean commentabled;

    /**
     * Database Column Remarks:
     *   博客评论次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.blog_comments
     *
     * @mbg.generated
     */
    private Integer blogComments;

    /**
     * Database Column Remarks:
     *   博客点赞次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.blog_likes
     *
     * @mbg.generated
     */
    private Integer blogLikes;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   删除标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.del_flag
     *
     * @mbg.generated
     */
    private Boolean delFlag;

    /**
     * Database Column Remarks:
     *   删除时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.del_time
     *
     * @mbg.generated
     */
    private Date delTime;

    /**
     * Database Column Remarks:
     *   博客内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.blog_content
     *
     * @mbg.generated
     */
    private String blogContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_blog
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}