package com.jicl.entity;

import java.io.Serializable;
import java.util.Date;

import lombok.Builder;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_comment
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
@Builder
public class Comment implements Serializable {
    /**
     * Database Column Remarks:
     *   评论id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.comment_id
     *
     * @mbg.generated
     */
    private Integer commentId;

    /**
     * Database Column Remarks:
     *   评论用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   评论的博客id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.blog_id
     *
     * @mbg.generated
     */
    private Integer blogId;

    /**
     * Database Column Remarks:
     *   评论时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.comment_time
     *
     * @mbg.generated
     */
    private Date commentTime;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   删除标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.del_flag
     *
     * @mbg.generated
     */
    private Boolean delFlag;

    /**
     * Database Column Remarks:
     *   评论内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.comment_content
     *
     * @mbg.generated
     */
    private String commentContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_comment
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}