package com.jicl.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_message
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Message implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.message_id
     *
     * @mbg.generated
     */
    private Long messageId;

    /**
     * Database Column Remarks:
     *   游客保存为IP地址，用户保存为用户编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.message_name
     *
     * @mbg.generated
     */
    private String messageName;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   留言内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.message_content
     *
     * @mbg.generated
     */
    private String messageContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_message
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.message_id
     *
     * @return the value of t_message.message_id
     *
     * @mbg.generated
     */
    public Long getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.message_id
     *
     * @param messageId the value for t_message.message_id
     *
     * @mbg.generated
     */
    public void setMessageId(Long messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.message_name
     *
     * @return the value of t_message.message_name
     *
     * @mbg.generated
     */
    public String getMessageName() {
        return messageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.message_name
     *
     * @param messageName the value for t_message.message_name
     *
     * @mbg.generated
     */
    public void setMessageName(String messageName) {
        this.messageName = messageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.create_time
     *
     * @return the value of t_message.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.create_time
     *
     * @param createTime the value for t_message.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.message_content
     *
     * @return the value of t_message.message_content
     *
     * @mbg.generated
     */
    public String getMessageContent() {
        return messageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.message_content
     *
     * @param messageContent the value for t_message.message_content
     *
     * @mbg.generated
     */
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent;
    }
}