package com.jicl.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_message
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class Message implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.message_id
     *
     * @mbg.generated
     */
    private Integer messageId;

    /**
     * Database Column Remarks:
     *   存储已经登录的用户id，否则为0
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.message_user_id
     *
     * @mbg.generated
     */
    private Integer messageUserId;

    /**
     * Database Column Remarks:
     *   留言者昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.message_nickname
     *
     * @mbg.generated
     */
    private String messageNickname;

    /**
     * Database Column Remarks:
     *   留言者邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.message_email
     *
     * @mbg.generated
     */
    private String messageEmail;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   删除标志：1-删除 0-未删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.del_flag
     *
     * @mbg.generated
     */
    private Boolean delFlag;

    /**
     * Database Column Remarks:
     *   删除时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.del_time
     *
     * @mbg.generated
     */
    private Date delTime;

    /**
     * Database Column Remarks:
     *   留言内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.message_content
     *
     * @mbg.generated
     */
    private String messageContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_message
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}