package com.jicl.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_message
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class Message implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.message_id
     *
     * @mbg.generated
     */
    private Long messageId;

    /**
     * Database Column Remarks:
     *   游客保存为IP地址，用户保存为用户编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.message_name
     *
     * @mbg.generated
     */
    private String messageName;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   留言内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.message_content
     *
     * @mbg.generated
     */
    private String messageContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_message
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}