package com.jicl.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_reply
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class Reply implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.reply_id
     *
     * @mbg.generated
     */
    private Integer replyId;

    /**
     * Database Column Remarks:
     *   回复的用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   回复时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.reply_time
     *
     * @mbg.generated
     */
    private Date replyTime;

    /**
     * Database Column Remarks:
     *   被回复的用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.replied_user_id
     *
     * @mbg.generated
     */
    private Integer repliedUserId;

    /**
     * Database Column Remarks:
     *   回复内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.reply_content
     *
     * @mbg.generated
     */
    private String replyContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_reply
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}