package com.jicl.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_reply
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Reply implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.reply_id
     *
     * @mbg.generated
     */
    private Integer replyId;

    /**
     * Database Column Remarks:
     *   回复的用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   回复时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.reply_time
     *
     * @mbg.generated
     */
    private Date replyTime;

    /**
     * Database Column Remarks:
     *   被回复的用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.replied_user_id
     *
     * @mbg.generated
     */
    private Integer repliedUserId;

    /**
     * Database Column Remarks:
     *   回复内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reply.reply_content
     *
     * @mbg.generated
     */
    private String replyContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_reply
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.reply_id
     *
     * @return the value of t_reply.reply_id
     *
     * @mbg.generated
     */
    public Integer getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.reply_id
     *
     * @param replyId the value for t_reply.reply_id
     *
     * @mbg.generated
     */
    public void setReplyId(Integer replyId) {
        this.replyId = replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.user_id
     *
     * @return the value of t_reply.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.user_id
     *
     * @param userId the value for t_reply.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.reply_time
     *
     * @return the value of t_reply.reply_time
     *
     * @mbg.generated
     */
    public Date getReplyTime() {
        return replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.reply_time
     *
     * @param replyTime the value for t_reply.reply_time
     *
     * @mbg.generated
     */
    public void setReplyTime(Date replyTime) {
        this.replyTime = replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.replied_user_id
     *
     * @return the value of t_reply.replied_user_id
     *
     * @mbg.generated
     */
    public Integer getRepliedUserId() {
        return repliedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.replied_user_id
     *
     * @param repliedUserId the value for t_reply.replied_user_id
     *
     * @mbg.generated
     */
    public void setRepliedUserId(Integer repliedUserId) {
        this.repliedUserId = repliedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reply.reply_content
     *
     * @return the value of t_reply.reply_content
     *
     * @mbg.generated
     */
    public String getReplyContent() {
        return replyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reply.reply_content
     *
     * @param replyContent the value for t_reply.reply_content
     *
     * @mbg.generated
     */
    public void setReplyContent(String replyContent) {
        this.replyContent = replyContent;
    }
}