package com.jicl.mapper;

import com.jicl.entity.Announcement;
import com.jicl.entity.AnnouncementExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AnnouncementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    long countByExample(AnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    int deleteByExample(AnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer anncId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    int insert(Announcement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    int insertSelective(Announcement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    List<Announcement> selectByExampleWithBLOBs(AnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    List<Announcement> selectByExample(AnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    Announcement selectByPrimaryKey(Integer anncId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Announcement record, @Param("example") AnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Announcement record, @Param("example") AnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Announcement record, @Param("example") AnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Announcement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Announcement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_announcement
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Announcement record);
}